### ISSUE TITLE
Allow different input formats

### ISSUE THREAD

**Issue by miguelgrc** [Arquisoft/citizensLoader_i2b#10]
_From 1st deliverable document:_

> The input data parser can be configured to accept data in different formats. Although
it is mandatory to import data in Excel format, the system should be ready to be extended in the
future to accept other formats easily

**Comment by nicolaspascual** [comment]
This is done. I placed an strategy in the state in order to be easily upgrade. The new classes must implement the CellLikeDataContainer Interface
